name: Build FlashPatch

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install .NET Framework 4.5 Developer Pack
        run: |
          choco install netfx-4.5.2-devpack -y
      - name: Build executable
        shell: powershell
        working-directory: FlashPatch
        run: >
          msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin FlashPatch.csproj
      - uses: actions/upload-artifact@v7
        with:
          name: FlashPatch
          path: FlashPatch/bin/FlashPatch.exe
